### ISSUE TITLE
Add the functionality to create and add rooms and beds for a ward

### ISSUE THREAD

**Issue by SnehaR26** [charludo/ycms#77] opened 2023-11-30 22:18 UTC
### Motivation

Currently ZBM user can only add a ward . We want them to be able to add rooms and subsequently beds in those rooms.

### User Story

For achieving a complete functionality of our product, we should have this feature.
### Proposed Solution

Adding a form / appending ward form
### Additional Context

should be able to add multiple beds/rooms with a single submission. User shouldn't have to click multiple times.

**Comment by charludo** [comment] 2023-12-04 09:46
This is a duplicate of #73. But since you've added more detail here, I will close that one as duplicate. Here's the proposed solution from #73:

- add a field "number of rooms"
- display according number of "rooms" below that, preset to two beds, with up/down arrows (or something like that)
-  should be updated in real time through JS

Something else to consider: All room and bed settings need to be made here. I.e. the room number is settable, the bed type, etc. It would probably make sense to pre-set those fields with sensible default values.

**Closed as completed** 2024-01-17 18:46 UTC
Labels: feature, prio: medium
